spring.application.name=balestrinimoveis

spring.datasource.url=jdbc:mysql://localhost:3306/balestrinimoveisdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

aws.s3.bucket-name=seu-nome-de-bucket-exclusivo-aqui
aws.region=sa-east-1

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}


